Lidar_front_end:
   lidar_type: 3   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 16
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 752 #1280
   image_height: 480 #1024
   camera_intrinsic:
         [425.0258563372763, 0, 386.0151866550880,
         0, 426.7976260903337, 241.9130336743440,
         0.0, 0.0, 1.0 ] 
         # [863.4241, 0.0, 640.6808,
         # 0.0,  863.4171, 518.3392,
         # 0.0, 0.0, 1.0 ]
   
   # Calculated from MATLAB stereoCameraCalibrator using calib_stereo dataset: k1, k2, k3 -0.312793405695452	0.128165059168011	-0.0285839754739671
   # using k1 and k2 from provided parameters in eee_03 dataset , camera_left.yaml
   camera_dist_coeffs: [-0.288105327549552, 0.074578284234601, 7.784489598138802e-04, -2.277853975035461e-04, -0.0285839754739671]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R:
         [0.02183084, -0.01312053,  0.99967558,
           0.99975965,  0.00230088, -0.02180248,
          -0.00201407,  0.99991127,  0.01316761]
   camera_ext_t: [0.00552943,-0.12431302,0.01614686]
   # camera_ext_t: [0.12431302,-0.00552943,-0.01614686]
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30
